########## Homebrew ##########
export PATH=/opt/homebrew/bin:$PATH

# Case insensitive tab completion
zstyle ':completion:*' matcher-list 'm:{a-zA-Z}={A-Za-z}'
# Auto load suggestions when correcting case
setopt MENU_COMPLETE
setopt share_history

# Set custom prompt
PROMPT='%F{green}%2d > '
# Set a cache dir
export ZSH_CACHE_DIR=$HOME/.zsh/cache

# Reload completions
autoload -Uz compinit

for dump in ~/.zcompdump(N.mh+24); do
  compinit
done

compinit -C

# Statically load plugins from antibody (generated by antibody/install.sh)
source ~/.zsh_plugins.sh

# Init rbenv
# export PATH="$HOME/.rbenv/bin:$PATH"
# eval "$(rbenv init -)"

# Init conda
# source ~/miniconda/etc/profile.d/conda.sh

# Aliases
deti() {
  docker run --rm -it --entrypoint "/bin/bash" "$1"
}

########## GPG setup for SSH ##########

# Set an environment variable to tell GPG the current terminal.
# NOTE: This is needed to ensure the pin entry prompt goes to the correct TTY
export GPG_TTY=$(tty)

# Start gpg-agent, if it isn't started already
gpgconf --launch gpg-agent
SERIAL=$(gpg-connect-agent 'scd serialno' /bye | head -n 1 | cut -f3 -d' ')
gpg-connect-agent "scd checkpin $SERIAL" /bye > /dev/null
# gpg-connect-agent updatestartuptty /bye > /dev/null

# https://developer.okta.com/blog/2021/07/07/developers-guide-to-gpg#enable-your-gpg-key-for-ssh

########## End GPG setup for SSH ##########

eval "$(fnm env --use-on-cd)"
# Computer specific enviroment config
# source ~/.zshrc_extensions
