# Case insensitive tab completion
zstyle ':completion:*' matcher-list 'm:{a-zA-Z}={A-Za-z}'
# Auto load suggestions when correcting case
setopt MENU_COMPLETE

# Reload completions
autoload -Uz compinit && compinit

# Statically load plugins from antibody (generated by antibody/install.sh)
source ~/.zsh_plugins.sh
